UI/MikroservicesUI/Models/BurgerViewModel.cs
namespace MikroservicesUI.Models
{
    public class BurgerViewModel
    {
        public int BurgerID { get; set; }
        public string Name { get; set; }
        public decimal Price { get; set; }
        public string Description { get; set; }
    }
}

UI/MikroservicesUI/Controllers/BurgerController.cs
using Microsoft.AspNetCore.Mvc;
using MikroservicesUI.Models;
using Newtonsoft.Json;
using System.Text;

namespace MikroservicesUI.Controllers
{
    public class BurgerController : Controller
    {
        private readonly IHttpClientFactory _httpClientFactory;

        public BurgerController(IHttpClientFactory httpClientFactory)
        {
            _httpClientFactory = httpClientFactory;
        }

        [HttpGet]
        public async Task<IActionResult> AllBurgerList()
        {
            var client = _httpClientFactory.CreateClient();
            var responseMessage = await client.GetAsync("http://localhost:8001/api/Burger");
            if (responseMessage.IsSuccessStatusCode)
            {
                var data = await responseMessage.Content.ReadAsStringAsync();
                var convertData = JsonConvert.DeserializeObject<List<BurgerViewModel>>(data);
                return View(convertData);
            }
            return View();
        }

        [HttpGet]
        public IActionResult AddBurger()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> AddBurger(BurgerViewModel burger)
        {
            var client = _httpClientFactory.CreateClient();
            var data = JsonConvert.SerializeObject(burger);
            StringContent content = new StringContent(data, Encoding.UTF8, "application/json");
            var responseMessage = await client.PostAsync("http://localhost:8001/api/Burger", content);
            if (responseMessage.IsSuccessStatusCode)
            {
                TempData["Success"] = "Burger updated!";
                return RedirectToAction("AllBurgerList");
            }
            return View();
        }

        public async Task<IActionResult> DeleteBurgerInfo(int id)
        {
            var client = _httpClientFactory.CreateClient();
            var responseMessage = await client.DeleteAsync($"http://localhost:8001/api/Burger/{id}");
            if (responseMessage.IsSuccessStatusCode)
                return RedirectToAction("AllBurgerList");
            else
            {
                TempData["Error"] = "Burger is not deleted!";
                return RedirectToAction("AllBurgerList");
            }

        }

        [HttpGet]
        public async Task<IActionResult> EditBurgerInfo(int id)
        {
            var client = _httpClientFactory.CreateClient();
            var responseMessage = await client.GetAsync($"http://localhost:8001/api/Burger/{id}");
            if (responseMessage.IsSuccessStatusCode)
            {
                var data = await responseMessage.Content.ReadAsStringAsync();
                var convertData = JsonConvert.DeserializeObject<BurgerViewModel>(data);
                return View(convertData);
            }

            else
            {
                ViewBag.Error = "Currently unavailable! Try again a few minutes after.";
                return RedirectToAction("AllBurgerList");
            }
        }

        [HttpPost]
        public async Task<IActionResult> EditBurgerInfo(BurgerViewModel burger)
        {
            var client = _httpClientFactory.CreateClient();
            var data = JsonConvert.SerializeObject(burger);
            StringContent content = new StringContent(data, Encoding.UTF8, "application/json");
            var responseMessage = await client.PutAsync("http://localhost:8001/api/Burger", content);
            if (responseMessage.IsSuccessStatusCode)
            {
                TempData["Success"] = "Burger updated!";
                return RedirectToAction("AllBurgerList");
            }
            else
            {
                TempData["Error"] = "Burger is not updated! Try again a few minutes after.";
                return View();
            }

        }
    }
}

UI/MikroservicesUI/Views/Burger/AddBurger.cshtml
@model BurgerViewModel
@{
    ViewData["Title"] = "AddBurger";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="col-xl-12 col-lg-12">
    <div class="card">
        <div class="card-header">
            <h4 class="card-title">BURGER</h4>
        </div>
        <div class="card-body">
            <div class="basic-form">
                <form method="post" enctype="multipart/form-data" asp-action="AddBurger" asp-controller="Burger">
                    <div class="form-group row">
                        <label class="col-sm-2 col-form-label col-form-label-sm">NAME</label>
                        <div class="col-sm-10">
                            <input type="text" asp-for="Name" class="form-control form-control-sm" placeholder="Burger Name">
                        </div>
                    </div>
                    <div class="form-group row">
                        <label class="col-sm-2 col-form-label">PRICE</label>
                        <div class="col-sm-10">
                            <input type="text" asp-for="Price" class="form-control" placeholder="Burger Unit Price">
                        </div>
                    </div>
                    <div class="form-group row">
                        <label class="col-sm-2 col-form-label">DECRIPTION</label>
                        <div class="col-sm-10">
                            <textarea asp-for="Description" class="form-control" cols="3" rows="3" placeholder="Burger Description"></textarea>

                        </div>
                    </div>
                    <button type="submit" class="btn btn-info">
                        ADD BURGER
                        <span class="btn-icon-right"><i class="fa fa-heart"></i></span>
                    </button>
                </form>
            </div>
        </div>
    </div>
</div>

UI/MikroservicesUI/Views/Burger/AllBurgerList.cshtml
@model List<BurgerViewModel>
@{
    ViewData["Title"] = "AllBurgerList";
    Layout = "~/Views/Shared/_Layout.cshtml";
    int count = 0;
}

<div class="row">
    <div class="col-lg-12">
        <div class="card">
            <div class="card-header">
                <h4 class="card-title">BURGER LIST</h4>
            </div>
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table table-responsive-md">
                        <thead>
                            <tr>
                                <th class="width80">#</th>
                                <th>NAME</th>
                                <th>PRICE</th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model)
                            {
                                count++;
                                <tr>
                                    <td><strong>@count</strong></td>
                                    <td>@item.Name</td>
                                    <td>@item.Price</td>
                                    <td>
                                        <div class="dropdown">
                                            <button type="button" class="btn btn-success light sharp" data-toggle="dropdown">
                                                <svg width="20px" height="20px" viewBox="0 0 24 24" version="1.1"><g stroke="none" stroke-width="1" fill="none" fill-rule="evenodd"><rect x="0" y="0" width="24" height="24" /><circle fill="#000000" cx="5" cy="12" r="2" /><circle fill="#000000" cx="12" cy="12" r="2" /><circle fill="#000000" cx="19" cy="12" r="2" /></g></svg>
                                            </button>
                                            <div class="dropdown-menu">
                                                <a class="dropdown-item" href="/Burger/EditBurgerInfo/@item.BurgerID">EDIT</a>
                                                <a class="dropdown-item" href="/Burger/DeleteBurgerInfo/@item.BurgerID">DELETE</a>
                                            </div>
                                        </div>
                                    </td>
                                </tr>
                            }

                        </tbody>
                    </table>
                    <a class="btn btn-info" href="/Burger/AddBurger/">
                        ADD NEW BURGER
                        <span class="btn-icon-right"><i class="fa fa-heart"></i></span>
                    </a>
                </div>
            </div>
        </div>
    </div>
</div>

UI/MikroservicesUI/Views/Burger/EditBurgerInfo.cshtml
@model BurgerViewModel
@{
    ViewData["Title"] = "EditBurgerInfo";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div class="col-xl-12 col-lg-12">
    <div class="card">
        <div class="card-header">
            <h4 class="card-title">BURGER</h4>
        </div>
        <div class="card-body">
            <div class="basic-form">
                <form method="post">
                    <input type="hidden" asp-for="BurgerID" />
                    <div class="form-group row">
                        <label class="col-sm-2 col-form-label col-form-label-sm">NAME</label>
                        <div class="col-sm-10">
                            <input type="text" asp-for="Name" class="form-control form-control-sm" placeholder="Burger Name">
                        </div>
                    </div>
                    <div class="form-group row">
                        <label class="col-sm-2 col-form-label">PRICE</label>
                        <div class="col-sm-10">
                            <input type="text" asp-for="Price" class="form-control" placeholder="Burger Unit Price">
                        </div>
                    </div>
                    <div class="form-group row">
                        <label class="col-sm-2 col-form-label">DECRIPTION</label>
                        <div class="col-sm-10">
                            <textarea asp-for="Description" class="form-control" cols="3" rows="3" placeholder="Burger Description">
                                </textarea>

                        </div>
                    </div>
                    <button type="submit" class="btn btn-info">
                        UPDATE BURGER
                        <span class="btn-icon-right"><i class="fa fa-heart"></i></span>
                    </button>
                </form>
            </div>
        </div>
    </div>
</div>